import type { ApprovalRequest } from '../types/approvalRequest';

export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: 1,
    targetType: 'COURSE',
    targetId: 'course-001',
    targetTitle: 'Lập trình React cơ bản',
    requestType: 'CREATE',
    decision: 'PENDING',
    feedback: null,
    createdBy: 'staff-001',
    createdAt: '2024-01-15T09:30:00Z',
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: 2,
    targetType: 'CHAPTER',
    targetId: 'chapter-001',
    targetTitle: 'Chương 1: Giới thiệu về React',
    requestType: 'UPDATE',
    decision: 'APPROVED',
    feedback: 'Nội dung rất tốt, phê duyệt ngay!',
    createdBy: 'staff-002',
    createdAt: '2024-01-14T14:20:00Z',
    reviewedBy: 'manager-001',
    reviewedAt: '2024-01-14T16:45:00Z',
  },
  {
    id: 3,
    targetType: 'UNIT',
    targetId: 'unit-001',
    targetTitle: 'Bài 1: Cài đặt React',
    requestType: 'CREATE',
    decision: 'REJECTED',
    feedback: 'Nội dung còn chưa đầy đủ, cần bổ sung thêm ví dụ thực tế.',
    createdBy: 'staff-003',
    createdAt: '2024-01-13T11:15:00Z',
    reviewedBy: 'manager-001',
    reviewedAt: '2024-01-13T13:30:00Z',
  },
  {
    id: 4,
    targetType: 'COURSE',
    targetId: 'course-002',
    targetTitle: 'JavaScript nâng cao',
    requestType: 'UPDATE',
    decision: 'PENDING',
    feedback: null,
    createdBy: 'staff-001',
    createdAt: '2024-01-12T08:45:00Z',
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: 5,
    targetType: 'CHAPTER',
    targetId: 'chapter-002',
    targetTitle: 'Chương 2: State và Props',
    requestType: 'DELETE',
    decision: 'PENDING',
    feedback: null,
    createdBy: 'staff-002',
    createdAt: '2024-01-11T16:20:00Z',
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: 6,
    targetType: 'UNIT',
    targetId: 'unit-002',
    targetTitle: 'Bài 2: Sử dụng Hooks',
    requestType: 'UPDATE',
    decision: 'APPROVED',
    feedback: 'Cập nhật tốt, giữ nguyên hướng này.',
    createdBy: 'staff-003',
    createdAt: '2024-01-10T10:30:00Z',
    reviewedBy: 'manager-002',
    reviewedAt: '2024-01-10T15:15:00Z',
  },
  {
    id: 7,
    targetType: 'COURSE',
    targetId: 'course-003',
    targetTitle: 'TypeScript cho người mới bắt đầu',
    requestType: 'CREATE',
    decision: 'PENDING',
    feedback: null,
    createdBy: 'staff-004',
    createdAt: '2024-01-09T13:45:00Z',
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: 8,
    targetType: 'CHAPTER',
    targetId: 'chapter-003',
    targetTitle: 'Chương 3: Lifecycle Methods',
    requestType: 'DELETE',
    decision: 'REJECTED',
    feedback: 'Không thể xóa chương này vì còn nhiều học viên đang học.',
    createdBy: 'staff-001',
    createdAt: '2024-01-08T09:20:00Z',
    reviewedBy: 'manager-001',
    reviewedAt: '2024-01-08T11:45:00Z',
  },
  {
    id: 9,
    targetType: 'UNIT',
    targetId: 'unit-003',
    targetTitle: 'Bài 3: Event Handling',
    requestType: 'CREATE',
    decision: 'APPROVED',
    feedback: 'Nội dung chi tiết và dễ hiểu.',
    createdBy: 'staff-002',
    createdAt: '2024-01-07T14:10:00Z',
    reviewedBy: 'manager-002',
    reviewedAt: '2024-01-07T16:30:00Z',
  },
  {
    id: 10,
    targetType: 'COURSE',
    targetId: 'course-004',
    targetTitle: 'Node.js và Express',
    requestType: 'UPDATE',
    decision: 'PENDING',
    feedback: null,
    createdBy: 'staff-004',
    createdAt: '2024-01-06T12:00:00Z',
    reviewedBy: null,
    reviewedAt: null,
  },
];

export default mockApprovalRequests;
