name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # Tạo env build-time cho Vite (không commit file này)
      - name: Create production env file for Vite
        run: |
          echo "VITE_API_BASE_URL=https://webapp-apjf-be-d5dpgucvaqddexb9.southeastasia-01.azurewebsites.net/api" > .env.production
          echo "VITE_AI_URL=https://webapp-apjf-ai-YOUR_ACTUAL_AI_BACKEND.southeastasia-01.azurewebsites.net/api" >> .env.production

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Đổi tên secret này trùng với secret bạn tạo trong repo settings
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"       # nơi có package.json
          api_location: ""        # không dùng API Functions
          output_location: "dist" # output của Vite
        env:
          NODE_ENV: production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"