name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # Set up Node.js với version phù hợp với Vite 7
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # Set up npm authentication (optional, only if NPM_TOKEN exists)  
      - name: Set up npm auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -n "$NPM_TOKEN" ]; then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "NPM authentication configured"
          else
            echo "No NPM_TOKEN found, proceeding without authentication"
          fi

      # Install dependencies with retry mechanism
      - name: Install dependencies with retry
        run: |
          # First try npm ci with retries
          for i in 1 2 3; do
            echo "npm ci attempt $i of 3..."
            if npm ci --prefer-offline --no-audit --no-fund; then
              echo "npm ci succeeded on attempt $i"
              exit 0
            else
              echo "npm ci failed on attempt $i"
              if [ $i -lt 3 ]; then
                echo "Waiting 15 seconds before retry..."
                sleep 15
              fi
            fi
          done
          
          # Fallback to npm install if npm ci fails
          echo "npm ci failed after 3 attempts, trying npm install as fallback..."
          for i in 1 2; do
            echo "npm install attempt $i of 2..."
            if npm install --no-audit --no-fund; then
              echo "npm install succeeded on attempt $i"
              exit 0
            else
              echo "npm install failed on attempt $i"
              if [ $i -lt 2 ]; then
                echo "Waiting 20 seconds before retry..."
                sleep 20
              fi
            fi
          done
          
          echo "All installation methods failed"
          exit 1

      # Build project
      - name: Build project
        run: npm run build
        env:
          VITE_API_BASE_URL: https://webapp-apjf-be-d5dpgucvaqddexb9.southeastasia-01.azurewebsites.net/api
          VITE_AI_URL: https://webapp-apjf-rag-f6c8ffb8djd6c6b9.southeastasia-01.azurewebsites.net/api

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_FLOWER_075752300 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          api_location: "" 
          output_location: "dist"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_FLOWER_075752300 }}
          action: "close"
          app_location: "/"